### ISSUE TITLE
YAAW for Safari

### ISSUE THREAD

**Issue by wao1201** [acgotaku/YAAW-for-Chrome#1]
请问是否有计划针对 Safari 做一个插件：
只需要有 “右键菜单添加到 YAAW/aria2” 就可以了

谢谢

**Comment by acgotaku** [comment]
先赞助我一台Mac！ @Cee

**Comment by Cee** [comment]
我来看看，是对单个文件吗？@wao1201

**Comment by wao1201** [comment]
@Cee 对的，就是类似一般下载软件会在浏览器右键菜单添加的那样

谢谢！

**Comment by wao1201** [comment]
@Cee 搜了下，只发现个针对 chrome 的插件有类似功能 https://github.com/robbielj/chrome-aria2-integration
不知对您是否有参考价值
谢谢
