### ISSUE TITLE
YAAW管理页面报错Error: Unauthorized

### ISSUE THREAD

**Issue by alanwonder** [acgotaku/YAAW-for-Chrome#10]
win7 chrome 51.0.2704.63 m
设置里RPC地址使用了如下格式：
http://token:secret@hostname:port/jsonrpc
打开YAAW管理页面报错Error: Unauthorized

**Comment by acgotaku** [comment]
不带认证就没问题？ 还是 实际参数写错了？

**Comment by alanwonder** [comment]
不带认证就好的，参数没有问题，在你的百度云插件里带认证也可以用的

**Comment by acgotaku** [comment]
你的参数 是公网地址么？ 不介意的话 我可以测试测试。。。

**Comment by acgotaku** [comment]
就是百度云点击测试通讯是没有问题的 但是 YAAW却出问题了？ 
https://binux.github.io/yaaw/demo/ 你用这个试试？

**Comment by alanwonder** [comment]
是的百度云测试通讯成功的，参数是本地局域网的地址，公网的这个YAAW怎么添加参数呢？我平时用ziahamza的aria2 webui 应该不会影响到yaaw吧，我回去把aria2的版本更新一下再试试看

**Comment by acgotaku** [comment]
公网的和插件带的是一个用法

**Comment by alanwonder** [comment]
我用这个参数可以正常通讯http://binux.github.io/yaaw/demo/#path=http://token:XXXXXX@localhost:6800/jsonrpc
如果把意思连接改成https的就会包internal server error

**Comment by alanwonder** [comment]
我用这个参数可以正常通讯http://binux.github.io/yaaw/demo/#path=http://token:XXXXXX@localhost:6800/jsonrpc
如果把连接改成https的就会包internal server error

**Comment by alanwonder** [comment]
问题解决了，是我设置的问题，之前没有用过yaaw以为只要在插件选项里设置rpc参数就可以，所以在yaaw没有设置
