### ISSUE TITLE
希望能添加设置密码选项

### ISSUE THREAD

**Issue by kingzleshe** [acgotaku/YAAW-for-Chrome#12]

**Comment by kingzleshe** [comment]
aria2 web-UI 如果不设置密码 会弹出不安装的提示很烦人 所以我就设置了密码
但是发现 YAAW插件暂时没这个功能

**Comment by acgotaku** [comment]
YAAW插件可以设置的啊 格式 是  http://username:passwd@hostname:port/jsonrpc

**Comment by kingzleshe** [comment]
> http://<token>password@hostname:port/jsonrpc
> 
另外一种是这样的嘛？

发自我的 iPhone

**Comment by acgotaku** [comment]
@kingzleshe 没看懂你的意思

**Comment by kingzleshe** [comment]
不好意思之前邮箱回复的 显示有问题

https://token:secret@127.0.01:6800/jsonrpc
token加密方式 是不是这个格式

**Comment by acgotaku** [comment]
@kingzleshe 对的
