### ISSUE TITLE
有没有可能在任务下载完成后显示个chrome通知

### ISSUE THREAD

**Issue by pingshunhuangalex** [acgotaku/YAAW-for-Chrome#13]
发现插件更新的时候chrome能自动有通知显示

如果同样的通知能在每个任务下载后都实现我觉得会更人性化 不知道实现起来是不是困难 谢谢

**Comment by acgotaku** [comment]
@pingshunhuangalex 你只要开着那个 YAAW的界面 下载完成就有提示

**Comment by pingshunhuangalex** [comment]
原来要开着的 有可能能不开着实现么？

**Comment by pingshunhuangalex** [comment]
刚试了一下 开着aria2-webui 下载结束还是没有通知 （我把代码指向我自己设置的ui了）这个通知功能是一定要YAAW界面才能用的吗？

**Comment by acgotaku** [comment]
@pingshunhuangalex 必须要开着的，而且是YAAW的才行  我不打算造轮子写个后台跑的啊。。。

**Comment by pingshunhuangalex** [comment]
好吧 我自己再琢磨琢磨 没看见YAAW里面有通知相关的啊 我还以为你YAAW就是直接从YAAW那边直接拿过来用的

**Comment by acgotaku** [comment]
@pingshunhuangalex 有部分修改。。。
