### ISSUE TITLE
作者，你谷歌应用商店地址失效了！怎么回事？

### ISSUE THREAD

**Issue by tea1111980** [acgotaku/YAAW-for-Chrome#138]
### 看图：

404. 出现了错误。

在此服务器上找不到请求的网址。 这就是我们所知道的全部信息。

![image](https://user-images.githubusercontent.com/16295097/81475677-49169380-9240-11ea-9454-43d7d4c1f2fb.png)

还有一个叫 Alex Hua 是不是你另一个号？他也发布了同样的应用。

**Comment by acgotaku** [comment]
不是我的号  谷歌说我应用的权限不对 给我下架了

**Comment by acgotaku** [comment]
我还没时间处理这件事情

**Comment by tea1111980** [comment]
> 我还没时间处理这件事情

会不会是 你的应用密钥跟之前的不是同一个造成的？ 安卓APP就有这个问题，一个密钥只更新一个应用。

**Comment by acgotaku** [comment]
不是的，是最近谷歌开始 手动 review所有应用了， 觉得我的App 申请了不需要的权限， 所以把我的下架了。。。

**Comment by tea1111980** [comment]
> 不是的，是最近谷歌开始 手动 review所有应用了， 觉得我的App 申请了不需要的权限， 所以把我的下架了。。。

额。。。还有这种事。为什么谷歌要这么搞啊？
