### ISSUE TITLE
鼠标放到连击数的图标上，稍微久一点connections浮动的提示就不消失了，一直存在

### ISSUE THREAD

**Issue by acalimit** [acgotaku/YAAW-for-Chrome#19]
鼠标停留超过1秒就不会消失了。好吧，其实不是什么大问题，强迫症犯了，希望下次更新顺便弄下。

**Comment by acgotaku** [comment]
给个截图？？

**Comment by acalimit** [comment]
![20170403234303](https://cloud.githubusercontent.com/assets/5378519/24617751/73966d88-18c7-11e7-9aec-7b10fe8cd7ee.png)
就是这样，进度条颜色希望能加灰一点，看不到那个白色的数字了。

**Comment by acgotaku** [comment]
这个你应该去YAAW提issue。。。 我只是搬运。。。

**Comment by acalimit** [comment]
那边作者都好久没更新过了。刷新时间改为1s就会这样，其他时间不会，估计是和bootstrap框架冲突了。
