### ISSUE TITLE
下载Mora的音乐文件显示导出下载成功，但是无法下载

### ISSUE THREAD

**Issue by kirito269** [acgotaku/YAAW-for-Chrome#2]
求加上例外网站QAQ

**Comment by acgotaku** [comment]
@kirito269 你这说的太含糊了 我都不知道是啥意思 给个截图啥的 好么

**Comment by kirito269** [comment]
![image](https://cloud.githubusercontent.com/assets/10243794/12004063/4dceae68-ab76-11e5-9b1a-be3cc3dba77f.png)

**Comment by kirito269** [comment]
![image](https://cloud.githubusercontent.com/assets/10243794/12004067/59f0514c-ab76-11e5-800f-23a0323fdc8a.png)

**Comment by kirito269** [comment]
点击下载链接时chrome会弹出自带的下载框，但是YAAW-for-Chrome显示已经在下载，能完全接管chrome的下载行为么？

**Comment by acgotaku** [comment]
@kirito269 你可以告诉我站点么 我亲自测试一下

**Comment by kirito269** [comment]
mora.jp 抱歉这么晚回复你 同时出现下载框和导出下载成功的情况
![image](https://cloud.githubusercontent.com/assets/10243794/12046337/49376596-aef2-11e5-9e55-191b59c89218.png)

**Comment by acgotaku** [comment]
@kirito269 这个其实你在设置里面关掉下载的时候选择位置就可以了 
这样就会直接托管 不会出现下载框 如果是无法正常下载的话 告诉我 哪里下载 的  我去测试

**Comment by kirito269** [comment]
@acgotaku  https://tusfiles.net/6kvzhbxghn4o 下载失败

**Comment by kirito269** [comment]
下载https://dl.google.com/dl/android/aosp/hammerhead-mmb29s-factory-6bfcdfa4.tgz 失败 
@acgotaku

**Comment by acgotaku** [comment]
@kirito269 这个问题经过分析 是因为谷歌API抓取失败导致的. 目前还没想到比较好的解决办法 
之后会加上 劫持下载白名单或 黑名单

**Comment by acgotaku** [comment]
@kirito269  更新啦~~~~

**Comment by kirito269** [comment]
谢谢秋水～(｡･ω･｡)ﾉ♡
