### ISSUE TITLE
关于Google Drive的拦截问题

### ISSUE THREAD

**Issue by shikkoku** [acgotaku/YAAW-for-Chrome#25]
我设置成大于等于20M的文件拦截，但是对Google Drive并没有卵用。直接调用了浏览器下载了……

**Comment by acgotaku** [comment]
Google 好像是自己JS处理的。。。。

**Comment by shikkoku** [comment]
那只能这样了？

**Comment by acgotaku** [comment]
分析了下 貌似并没有触发Chrome的下载API 所以现在也不是很好解决

**Comment by acgotaku** [comment]
0.2.0 版本可以拦截， 但是需要设置 fileSIze为 0
