### ISSUE TITLE
下载文件名问题反馈

### ISSUE THREAD

**Issue by shui288** [acgotaku/YAAW-for-Chrome#26]
1.下载youtube视频文件名是:seyyffhhsq，是一串英文并且没后缀名.mp4

2.下载百度网盘的中文压缩包名不是中文，是一串字符夹带英文字母

**Comment by acgotaku** [comment]
你是说百度网盘的文件下载？ youtube应该是用的 其他插件吧？

**Comment by shui288** [comment]
是的，是百度网盘的文件下载

yiutube是用SaveFrom.net helper_7.42显示下载按钮，然后用YAAW for Chrome_0.0.9下载， （这个插件:链接: https://pan.baidu.com/s/1kVfzgQr 密码: 6r9g
Aria2c Integration_1.7.0就没以上2个问题，可参考下，但它速好似没你的插件快而稳定，这个1.7.0不能接管4pda论坛的下载，下载只几k的文件）

谢谢！

**Comment by shui288** [comment]
youtube下视频的文件名：
videoplayback


百度下中文压缩包文件名：
5d3fd5e4383829c2284bad62d777e935


4pda论坛下载文件名：%DF%ED%E4%E5%EA%F1%2B%C1%F0%E0%F3%E7%E5%F0_v17.6.1.11%28170610011%29.apk

**Comment by shui288** [comment]
在这网址http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Android/492262/
下载的文件名是：
Android%2F492262%2Fchrome-android.zip

**Comment by acgotaku** [comment]
百度网盘为啥不用我写的exporter 反正用这个插件下载。。。

**Comment by acgotaku** [comment]
@shui288 貌似你用浏览器下载这个文件名也是不变的吧？ 还是 Android%2F492262%2Fchrome-android.zip

**Comment by shui288** [comment]
你写BaiduExporter-master_0.9.5也与YAAW for Chrome_0.0.9配套一起使用着。


其它接管正常下载文件名是:chrome-android.zip

**Comment by shui288** [comment]
@acgotaku 
如果能把这个插件（https://github.com/roooneey/chrome-aria2-integration）的下载文件名的技术移到yaaw来，就完美解决下载文件名乱码的问题了。

汉化版： （这个插件:链接: https://pan.baidu.com/s/1kVfzgQr 密码: 6r9g

**Comment by shui288** [comment]
YAAW-for-Chrome 0.1.0-------无论在线安装还是解压后安装，都无法安装，都显示“已被管理员禁止”，如何才能用上呢？

> 谢谢！
