### ISSUE TITLE
E-Hentai Archive下载导入错误

### ISSUE THREAD

**Issue by KirbyKFC** [acgotaku/YAAW-for-Chrome#27]
E-Hentai网站的Archive下载导入后的下载文件名是0 (正常的应该是标题+".zip")

尝试过不同文件大约20次下载，4次以文件名0或2下载成功，1次以正常文件名下载成功(只有这个文件名是全英文的，不知道是不是这个原因)，其他均为0进度下载失败。

使用chrome自带下载器下载正常，使用chrome扩展市场里xiami的aria2c integration能正常导入aria2c。

下载链接示例:
http://95.211.212.245/archive/1092852/030ff3ca57666453a5c08f54b70148374c6584a9/1502532304/0?start=1

**Comment by acgotaku** [comment]
我也不会用E HEntai啊。。。

**Comment by KirbyKFC** [comment]
那问一下黑名单能否只匹配链接里的"?start="

**Comment by KirbyKFC** [comment]
粗略看了下貌似模板已经定好了得再加一次匹配重新打包。
有打算添加自定义正则表达式的功能吗？
