### ISSUE TITLE
拦截 url 后导致 https://mega.nz 下载文件失败

### ISSUE THREAD

**Issue by livelazily** [acgotaku/YAAW-for-Chrome#3]
可否增加黑名单模式忽略某些url?

**Comment by chuyik** [comment]
国外网盘资源好像都这样，如 uploaded.net，用YAAW会导致资源下载失败。
测试地址：http://uploaded.net/file/hxr12ck2

**Comment by acgotaku** [comment]
是的 因为是跳转下载的 无法拦截 我之后会添加黑名单 和 白名单模式

**Comment by acgotaku** [comment]
@livelazily  @chuyik 加了白名单和 黑名单啦!

**Comment by river1** [comment]
这里的黑名单要怎么设置
我填进
mega.nz
还是会被拦截

**Comment by acgotaku** [comment]
@river1  https://mega.nz/  这样写

**Comment by river1** [comment]
这样写还是不行，而且我发现下载拦截打不打勾都会按文件大小拦截

**Comment by acgotaku** [comment]
@river1 可以给个例子么? 我来测试测试

**Comment by river1** [comment]
找了个[小文件](https://mega.nz/#!wR11TAbK!LZsmT3YEIfEbMZq6zHcW31RgRAEUjNfiHW4GeKt2RBA)

**Comment by acgotaku** [comment]
@river1 好吧 mega的下载确实比较特殊 我再进行特殊处理下吧

**Comment by acgotaku** [comment]
@river1 更新了新版本 看看~

**Comment by river1** [comment]
又试了几个，好像没问题了

**Comment by acgotaku** [comment]
@river1 那就好～
