### ISSUE TITLE
右键导出下载不支持 aria2 启用 rpc-secret 功能，提示下载失败

### ISSUE THREAD

**Issue by Drake-Z** [acgotaku/YAAW-for-Chrome#30]
不启用 rpc-secret 功能，JSON-RPC Path 为 http://localhost:6800/jsonrpc
右键导出下载正常。
启用 rpc-secret 功能，JSON-RPC Path 为 http://token:XXXXXXXXX@localhost:6800/jsonrpc
可以连接到 Aria2，但是右键导出下载会提示失败。

**Comment by JasonKhew96** [comment]
@Drake-Z 
YAAW跟右键的设定是分开的
![image](https://user-images.githubusercontent.com/29531167/32898644-ab4b5374-cb23-11e7-8d01-01b35601e95f.png)
![image](https://user-images.githubusercontent.com/29531167/32898713-d85336de-cb23-11e7-8f09-833ea6f6d78a.png)
