### ISSUE TITLE
黑白名单配置失效

### ISSUE THREAD

**Issue by pingshunhuangalex** [acgotaku/YAAW-for-Chrome#307]
以前好像就出现过这个问题，不过我一直没有在意。黑白名单好像失效了，或者我的用法不对。。。

我想要在Google Drive里禁用扩展，但是完全没有效果。我试了：
- *.google.com
- drive.google.com
- https://drive.google.com

似乎都不行。域名正确的写法是应该怎么写呢？谢谢

**Comment by acgotaku** [comment]
也有可能是 google触发的方式，没有被正确的截获，最有效的方法可能就是临时禁用扩展了。

**Comment by pingshunhuangalex** [comment]
我就是临时改的Threshold。没时间搞的话就把这个issue关了吧。

大佬还维护嘛？知道你超级忙的。Manifest v2明年就要被禁止运行了，不知道大佬有时间做下迁移不。否则这扩展明年就不能用了

**Comment by acgotaku** [comment]
我就是要升级到V3 才过来看看的，这个是我唯一上架的 扩展了，其他的都各种原因被谷歌下架了 ==

**Comment by pingshunhuangalex** [comment]
其它API的好办，就是这个插件用Vue写的，MV3的CSP不支持在`script-src`和`object-src`用'unsafe-eval'了。不知道是不是要用vanilla JS重写一遍

**Comment by acgotaku** [comment]
哈哈哈 我研究研究一下吧

**Comment by acgotaku** [comment]
依赖的 Vue 和 YAAW都不能在 V3运行，应该是升级不了了，V3终止的时候也就是这个插件寿命的终止吧。
