### ISSUE TITLE
增加原始下载地址查看

### ISSUE THREAD

**Issue by cute-angelia** [acgotaku/YAAW-for-Chrome#32]
很多情况需要把地址分享给别, 希望可以增加原始下载地址查看

**Comment by acgotaku** [comment]
4月应该会重构本项目 届时大家需要的功能都会加上

**Comment by shui288** [comment]
下载youtube  推特视频要加上输出中文名称，谢谢

**Comment by acgotaku** [comment]
针对右键导出的话 其实菜单里就可以直接复制
针对拦截 很多情况下 需要cookies  
所以这个功能  意义不大
