### ISSUE TITLE
希望能添加自定义下载路径的功能~

### ISSUE THREAD

**Issue by kukuhuihao** [acgotaku/YAAW-for-Chrome#39]
YAAW真的很方便平时在电脑端和服务器端的下载，不过因为下载都是下载到设置的默认路经里，下载的文件经常需要归档。如果能设置多个可选路径就好了~

https://ws4.sinaimg.cn/large/006tNbRwgy1fww42axyx9j31dk0rg77q.jpg

**Comment by acgotaku** [comment]
好的  我闲下来了就更新

**Comment by kukuhuihao** [comment]
期待期待！

**Comment by acgotaku** [comment]
0.2.0 版本 已发布
