### ISSUE TITLE
重复导入下载以及下载拦截设置问题

### ISSUE THREAD

**Issue by vacuum136** [acgotaku/YAAW-for-Chrome#4]
首先谢谢大大开发了如此好用的插件。使用过程中我碰到了几个问题：
1. 之前作为测试插件导入到YAAW中几个下载，随后将其删除。但是再随后的使用过程中，点击一个文件下载，右下方都会弹出多个信息说“导入成功”。看一眼YAAW发现，之前作为测试时下载的文件，又重新导入并开始下载了，将其暂停删除或者将其下载完成删除，后续依然会出现。为此我还重新安装了插件，但是问题依然存在。这个问题常常发生在打开浏览器后进行第一次下载时，让我很困惑。
2. 选项中的下载拦截勾选框逻辑貌似有些问题。如果没理解错，这个选项是拦截的总开关。但实际使用时，即使关闭拦截，只要当下载的文件大于设置的"File size"时，下载依然会被导入Aria2c。
希望大大看一下这两个问题，谢谢！

**Comment by acgotaku** [comment]
@vacuum136 这个问题确实存在 最近忙 没来得及更新 惭愧惭愧...

**Comment by vacuum136** [comment]
理解理解，没有关系~还好并不是有关功能的问题，只是希望这个插件更加完善。慢慢调试，期待你下次的更新 :-)

**Comment by acgotaku** [comment]
@vacuum136  更新了!!!
