### ISSUE TITLE
如果提示违规内容，点击导出下载时会报无效内容

### ISSUE THREAD

**Issue by kybetter** [acgotaku/YAAW-for-Chrome#40]
如果提示违规内容，点击导出下载时会报无效内容

**Comment by acgotaku** [comment]
不能描述详细点么？

**Comment by kybetter** [comment]
> 不能描述详细点么？

@acgotaku 
我百度云上的有些文件在使用百度云下载的时候被标记为违规内容了。
这时候我在页面中使用你的插件下载这部分内容，点导出下载的时候，就报 “无效内容”。

**Comment by acgotaku** [comment]
违规内容当然不能下载了。。 这有啥好报 issue的？

**Comment by kybetter** [comment]
:-O
