### ISSUE TITLE
加载已解压的扩展程序，发生错误 T T

### ISSUE THREAD

**Issue by kukuhuihao** [acgotaku/YAAW-for-Chrome#42]
https://ws1.sinaimg.cn/large/006tNc79gy1g2xuyc2pyij30tq09sq3o.jpg

**Comment by acgotaku** [comment]
??? 图片 403了

**Comment by pingshunhuangalex** [comment]
![image](https://user-images.githubusercontent.com/17170199/57577454-72300700-74ba-11e9-81a4-efec8c399b06.png)

**Comment by pingshunhuangalex** [comment]
设置页好像也出了点问题…… 这次好像变动比较大

![image](https://user-images.githubusercontent.com/17170199/57577564-41050600-74bd-11e9-82b2-28ed7b9a67ce.png)

**Comment by kukuhuihao** [comment]
@acgotaku 噢，是图床坏了...错误跟 @pingshunhuangalex 给出的一样~

**Comment by acgotaku** [comment]
直接加载 需要收到运行 build命令 生成 目标代码

**Comment by acgotaku** [comment]
还是推荐使用 官方商店安装

**Comment by pingshunhuangalex** [comment]
@acgotaku 谢了 build完就可以了

我看到`src`的时候就在想是不是要build，但是因为以前都不用的，所有有点不确定

希望以后还是能够保留直接加载的途径，因为我本地还自己改了改代码，如果直接从商店下就不太好改了

再次感谢，百忙之中又更新了

**Comment by acgotaku** [comment]
那我 写个 build教程吧

**Comment by kukuhuihao** [comment]
@acgotaku 感谢雪大添加的新功能~

**Comment by acgotaku** [comment]
@kukuhuihao 这个项目停更太久了  也该重构下代码了

**Comment by acgotaku** [comment]
https://github.com/acgotaku/YAAW-for-Chrome/blob/master/.github/CONTRIBUTING.md
