### ISSUE TITLE
开启该扩展后每个站点的第一次下载会不能正常弹出另存为对话框

### ISSUE THREAD

**Issue by loyle5** [acgotaku/YAAW-for-Chrome#43]
开启该扩展后每个站点的第一次下载会不能正常弹出另存为对话框
浏览器centbrower 内核Chromium 74.0.3729.169

**Comment by acgotaku** [comment]
应该使用自动下载选项会比较流畅

**Comment by acgotaku** [comment]
使用本插件的时候 不建议开启 每次下载提示询问下载位置 这个选项
