### ISSUE TITLE
下载拦截启用，但浏览器依然弹出另存为窗口？

### ISSUE THREAD

**Issue by cililianjie** [acgotaku/YAAW-for-Chrome#46]
RT

**Comment by acgotaku** [comment]
另存为窗口得自己手动在设置里关闭  扩展并没有操作这个的权限

还是说你用过类似软件可以不弹出？

**Comment by cililianjie** [comment]
> 另存为窗口得自己手动在设置里关闭 扩展并没有操作这个的权限
> 
> 还是说你用过类似软件可以不弹出？

原来这样啊，我以为拦截了就不应该弹出窗口。谢谢！
