### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by jiemo9527** [acgotaku/YAAW-for-Chrome#51]
后端正常运行，ariaNG已连接，右键导入普通http链接（已提前设置白名单）    https://github.com/acgotaku/YAAW-for-Chrome/blob/master/README.md

导出失败：无法连接到aria2c，导出下载任务失败。

**Comment by acgotaku** [comment]
在什么网站进行导出的? 导出之前有进行配置么 ？

**Comment by jiemo9527** [comment]
对普通的http链接导出，需要什么额外的配置吗？方便加QQ交流一下吗2569995914

**Comment by jiemo9527** [comment]
设置选项里好像没有填秘钥的地方

**Comment by jiemo9527** [comment]
插件是否不支持linux的文件目录

**Comment by jiemo9527** [comment]
已使用类似插件解决
