### ISSUE TITLE
图标上显示下载列表里的文件数量

### ISSUE THREAD

**Issue by river1** [acgotaku/YAAW-for-Chrome#6]
现在启用了下载拦截，按下下载之后没有任何反馈，用起来有点奇怪。如果在图标上加个下载计数，或者推送一个通知应该更友好一点。

**Comment by acgotaku** [comment]
@river1 点下载的话 应该会有通知的呀? 你把Chrome的系统通知功能关掉了?

**Comment by river1** [comment]
确实是的，原来在flag里面禁掉了

**Comment by acgotaku** [comment]
@river1 那就该没问题了吧~ (关掉这个issue吧
