### ISSUE TITLE
与插件“Save in...”有兼容问题

### ISSUE THREAD

**Issue by ShadyWhite** [acgotaku/YAAW-for-Chrome#63]
同时启用Save in...和YAAW时，Save in...会报错“此扩展程序无法将下载的文件命名为“”，因为另一扩展程序 (YAAW for Chrome) 已将此文件命名为“”。”
插件地址：https://chrome.google.com/webstore/detail/save-in%E2%80%A6/jpblofcpgfjikaapfedldfeilmpgkedf

**Comment by acgotaku** [comment]
保存文件的接口 只能被一个程序接管 所以使用的时候只能禁用一个了
