### ISSUE TITLE
从ftp下载时失败

### ISSUE THREAD

**Issue by JackTu** [acgotaku/YAAW-for-Chrome#7]
ftp要求用户名和密码，估计应该是要用到cookie，能否在设置里加上这个选项自动使用当前浏览器的cookie？

**Comment by acgotaku** [comment]
@JackTu  FTP是 Http head认证的 我已经加上了 cookies认证的了

**Comment by acgotaku** [comment]
最终决定还是不支持 FTP了。。。。
