### ISSUE TITLE
用自定义的文件路径取代YAAW

### ISSUE THREAD

**Issue by pingshunhuangalex** [acgotaku/YAAW-for-Chrome#8]
你好大神

我又来了 就是很快的问一下 有没有可能增加一个设置使得单击chrome插件的图标能够自动运行某个index文件而不是开启YAAW啊（其实就是把插件里的YAAW文件夹换成我自己的Aria2UI本地文件夹） 谢谢

**Comment by acgotaku** [comment]
目前还没有实现这个功能 这个也太小众了吧。。。

**Comment by pingshunhuangalex** [comment]
lol, 其实就我一个人需要吧 我以为只要把源码里YAAW文件夹 换成文件路径指向就好了 可能想当然了
