### ISSUE TITLE
无法调用Motrix下载工具

### ISSUE THREAD

**Issue by GalaxyZhu** [acgotaku/YAAW-for-Chrome#92]
您好，
我根据以下指引，打算添加Motrix下载工具到YAAW的设定中，但无法完成。
https://www.yuque.com/moapp/help/extensions

Motrix的指引为填入：
JSON-RPC | 使用 Motrix 下载 | http://127.0.0.1:16800/jsonrpc

但YAAW 0.2.2版本的设定只有
JSON-RPC | http://127.0.0.1:16800/jsonrpc

一旦下载，会显示调用失败。请问怎么解决？谢谢

**Comment by acgotaku** [comment]
你不会用 还要我读文档  教你？？

不就是把他的地址填到我插件里就完事了。。。

**Comment by tea1111980** [comment]
> 你不会用 还要我读文档 教你？？
> 
> 不就是把他的地址填到我插件里就完事了。。。

你最后果然还是教了，哈哈。。

**Comment by lizy0329** [comment]
> 您好，
> 我根据以下指引，打算添加Motrix下载工具到YAAW的设定中，但无法完成。
> https://www.yuque.com/moapp/help/extensions
> 
> Motrix的指引为填入：
> JSON-RPC | 使用 Motrix 下载 | http://127.0.0.1:16800/jsonrpc
> 
> 但YAAW 0.2.2版本的设定只有
> JSON-RPC | http://127.0.0.1:16800/jsonrpc
> 
> 一旦下载，会显示调用失败。请问怎么解决？谢谢

我懂你意思，根据语雀的文档打开 chrome-extension://dennnbdlpgjgbcjfgaohdahloollfgoc/options.html 进行 JSON-RPC 设置 http://127.0.0.1:16800/jsonrpc 完之后，再要点击 YAAW 插件的设置里设置 JSON-RPC
所以是要进行两步设置，文档写得实在是烂
